export type BrasileiraoTeamKey =
  | "athletico"
  | "atletico_mineiro"
  | "bahia"
  | "botafogo"
  | "chapecoense"
  | "corinthians"
  | "coritiba"
  | "cruzeiro"
  | "flamengo"
  | "fluminense"
  | "gremio"
  | "internacional"
  | "mirassol"
  | "palmeiras"
  | "red_bull_bragantino"
  | "remo"
  | "santos"
  | "sao_paulo"
  | "vasco_da_gama"
  | "vitoria";

export type BrasileiraoTeam = {
  key: BrasileiraoTeamKey;
  label: string;
  accent: string;
  logoUrl: string;
};

/** Auto-generated by scripts/extract_brasileirao_site_data.py */
export const BRASILEIRAO_TEAMS: BrasileiraoTeam[] = [
  {
    key: "athletico",
    label: "Athletico",
    accent: "#c8102e",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/679.png",
  },
  {
    key: "atletico_mineiro",
    label: "Atlético Mineiro",
    accent: "#1a1a1a",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/330.png",
  },
  {
    key: "bahia",
    label: "Bahia",
    accent: "#005ca9",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/1005.png",
  },
  {
    key: "botafogo",
    label: "Botafogo",
    accent: "#1f1f1f",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/537.png",
  },
  {
    key: "chapecoense",
    label: "Chapecoense",
    accent: "#006633",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/6790.png",
  },
  {
    key: "corinthians",
    label: "Corinthians",
    accent: "#1a1a1a",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/199.png",
  },
  {
    key: "coritiba",
    label: "Coritiba",
    accent: "#006633",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/776.png",
  },
  {
    key: "cruzeiro",
    label: "Cruzeiro",
    accent: "#0033a0",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/2036.png",
  },
  {
    key: "flamengo",
    label: "Flamengo",
    accent: "#c8102e",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/614.png",
  },
  {
    key: "fluminense",
    label: "Fluminense",
    accent: "#7a263a",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/2462.png",
  },
  {
    key: "gremio",
    label: "Grêmio",
    accent: "#0099d8",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/144.png",
  },
  {
    key: "internacional",
    label: "Internacional",
    accent: "#c8102e",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/6600.png",
  },
  {
    key: "mirassol",
    label: "Mirassol",
    accent: "#f4c430",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/10997.png",
  },
  {
    key: "palmeiras",
    label: "Palmeiras",
    accent: "#006437",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/1023.png",
  },
  {
    key: "red_bull_bragantino",
    label: "Red Bull Bragantino",
    accent: "#c8102e",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/8793.png",
  },
  {
    key: "remo",
    label: "Remo",
    accent: "#0033a0",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/10870.png",
  },
  {
    key: "santos",
    label: "Santos",
    accent: "#1a1a1a",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/221.png",
  },
  {
    key: "sao_paulo",
    label: "São Paulo",
    accent: "#c8102e",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/585.png",
  },
  {
    key: "vasco_da_gama",
    label: "Vasco da Gama",
    accent: "#1a1a1a",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/5370.png",
  },
  {
    key: "vitoria",
    label: "Vitória",
    accent: "#c8102e",
    logoUrl: "https://tmssl.akamaized.net/images/wappen/head/2125.png",
  },
];

export const BRASILEIRAO_TEAM_BY_KEY = Object.fromEntries(
  BRASILEIRAO_TEAMS.map((team) => [team.key, team]),
) as Record<BrasileiraoTeamKey, BrasileiraoTeam>;
