export type ReportPlayerRef = {
  playerId: string;
  positionFamily?: string;
  note?: string;
};

export type ReportPlayerGroup = {
  label?: string;
  players: ReportPlayerRef[];
};

export type PlayerReportCategory = {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  accent: string;
  groups: ReportPlayerGroup[];
};

export const POSITION_FAMILIES = [
  { key: "midfielders", label: "Meio-campistas", accent: "#34d399" },
  { key: "fullbacks", label: "Laterais", accent: "#a78bfa" },
] as const;

export type PositionFamilyKey = (typeof POSITION_FAMILIES)[number]["key"];

export const PROFILE_ALL_GROUP = {
  id: "all",
  title: "Todos os jogadores",
  subtitle: "Pool completo",
  description: "Top 30 meio-campistas e 30 laterais no Brasileirão 2026.",
  accent: "#cbd5e1",
} as const;

function p(playerId: string, positionFamily: PositionFamilyKey, note?: string): ReportPlayerRef {
  return { playerId, positionFamily, note };
}

/** Top 30 per position family — auto-generated by scripts/extract_brasileirao_site_data.py */
export const PLAYER_REPORT_CATEGORIES: PlayerReportCategory[] = [
  {
    id: "midfielders",
    title: "Meio-campistas",
    subtitle: "Top 30 meio-campistas",
    description: "Os 30 meio-campistas com melhor perfil de passe no Brasileirão 2026.",
    accent: "#34d399",
    groups: [
      {
        players: [
          p("132874", "midfielders"),
          p("611876", "midfielders"),
          p("329303", "midfielders"),
          p("1067671", "midfielders"),
          p("840202", "midfielders"),
          p("905453", "midfielders"),
          p("285949", "midfielders"),
          p("263477", "midfielders"),
          p("77726", "midfielders"),
          p("356514", "midfielders"),
          p("590262", "midfielders"),
          p("794927", "midfielders"),
          p("988851", "midfielders"),
          p("559034", "midfielders"),
          p("1145106", "midfielders"),
          p("1104068", "midfielders"),
          p("244591", "midfielders"),
          p("377238", "midfielders"),
          p("29735", "midfielders"),
          p("242213", "midfielders"),
          p("978563", "midfielders"),
          p("1008832", "midfielders"),
          p("922566", "midfielders"),
          p("1444694", "midfielders"),
          p("1064039", "midfielders"),
          p("1020375", "midfielders"),
          p("548030", "midfielders"),
          p("973533", "midfielders"),
          p("840398", "midfielders"),
          p("1656036", "midfielders"),
        ],
      },
    ],
  },
  {
    id: "fullbacks",
    title: "Laterais",
    subtitle: "Top 30 laterais",
    description: "Os 30 laterais com melhor perfil de passe no Brasileirão 2026.",
    accent: "#a78bfa",
    groups: [
      {
        players: [
          p("959620", "fullbacks"),
          p("795773", "fullbacks"),
          p("1019157", "fullbacks"),
          p("1087079", "fullbacks"),
          p("243113", "fullbacks"),
          p("928134", "fullbacks"),
          p("995071", "fullbacks"),
          p("931540", "fullbacks"),
          p("358956", "fullbacks"),
          p("261687", "fullbacks"),
          p("981452", "fullbacks"),
          p("243109", "fullbacks"),
          p("881110", "fullbacks"),
          p("84854", "fullbacks"),
          p("840119", "fullbacks"),
          p("870556", "fullbacks"),
          p("974512", "fullbacks"),
          p("1127439", "fullbacks"),
          p("1112484", "fullbacks"),
          p("981703", "fullbacks"),
          p("840500", "fullbacks"),
          p("311456", "fullbacks"),
          p("987589", "fullbacks"),
          p("1807816", "fullbacks"),
          p("252781", "fullbacks"),
          p("944459", "fullbacks"),
          p("335033", "fullbacks"),
          p("863292", "fullbacks"),
          p("311462", "fullbacks"),
          p("605528", "fullbacks"),
        ],
      },
    ],
  },
];

export function allReportPlayerRefs(): ReportPlayerRef[] {
  const seen = new Set<string>();
  const out: ReportPlayerRef[] = [];
  for (const category of PLAYER_REPORT_CATEGORIES) {
    for (const group of category.groups) {
      for (const player of group.players) {
        if (seen.has(player.playerId)) continue;
        seen.add(player.playerId);
        out.push(player);
      }
    }
  }
  return out;
}

export function totalReportCount(): number {
  return allReportPlayerRefs().length;
}

export type EnrichedReportPlayer = ReportPlayerRef & {
  category: PlayerReportCategory;
  groupLabel?: string;
  categoryIndex: number;
};

export function enrichedReportPlayers(): EnrichedReportPlayer[] {
  const out: EnrichedReportPlayer[] = [];
  for (const category of PLAYER_REPORT_CATEGORIES) {
    let categoryIndex = 0;
    for (const group of category.groups) {
      for (const player of group.players) {
        categoryIndex += 1;
        out.push({
          ...player,
          category,
          groupLabel: group.label,
          categoryIndex,
        });
      }
    }
  }
  return out;
}

export function playerIdsForProfileGroup(groupId: string): Set<string> {
  if (groupId === PROFILE_ALL_GROUP.id) {
    return new Set(allReportPlayerRefs().map((p) => p.playerId));
  }
  const category = PLAYER_REPORT_CATEGORIES.find((cat) => cat.id === groupId);
  if (!category) return new Set();
  const ids = new Set<string>();
  for (const group of category.groups) {
    for (const player of group.players) {
      ids.add(player.playerId);
    }
  }
  return ids;
}

export function profileGroupCounts(
  players: { player_id?: string | number | null }[],
): Record<string, number> {
  const available = new Set(players.map((p) => String(p.player_id)));
  const counts: Record<string, number> = {
    [PROFILE_ALL_GROUP.id]: players.length,
  };
  for (const category of PLAYER_REPORT_CATEGORIES) {
    const ids = playerIdsForProfileGroup(category.id);
    counts[category.id] = [...ids].filter((id) => available.has(id)).length;
  }
  return counts;
}

export function positionFamilyForPlayer(playerId: string): PositionFamilyKey | undefined {
  for (const category of PLAYER_REPORT_CATEGORIES) {
    const ids = playerIdsForProfileGroup(category.id);
    if (ids.has(playerId)) return category.id as PositionFamilyKey;
  }
  return undefined;
}
