export type ReportPlayerRef = {
  playerId: string;
  teamKey?: string;
  positionFamily?: string;
  note?: string;
};

export type ReportPlayerGroup = {
  label?: string;
  players: ReportPlayerRef[];
};

export type PlayerReportCategory = {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  accent: string;
  groups: ReportPlayerGroup[];
};

export const POSITION_FAMILY = "midfielders" as const;

export const PROFILE_ALL_GROUP = {
  id: "all",
  title: "Todos os jogadores",
  subtitle: "Pool completo",
  description: "Top 3 meio-campistas por time no Brasileirão 2026.",
  accent: "#cbd5e1",
} as const;

function p(playerId: string, teamKey: string, note?: string): ReportPlayerRef {
  return { playerId, teamKey, positionFamily: POSITION_FAMILY, note };
}

/** Top 3 midfielders per team — auto-generated by scripts/extract_brasileirao_site_data.py */
export const PLAYER_REPORT_CATEGORIES: PlayerReportCategory[] = [
  {
    id: "athletico",
    title: "Athletico",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Athletico no Brasileirão 2026.",
    accent: "#c8102e",
    groups: [
      {
        players: [
          p("980580", "athletico"),
          p("1485226", "athletico"),
          p("243651", "athletico"),
        ],
      },
    ],
  },
  {
    id: "atletico_mineiro",
    title: "Atlético Mineiro",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Atlético Mineiro no Brasileirão 2026.",
    accent: "#1a1a1a",
    groups: [
      {
        players: [
          p("1170954", "atletico_mineiro"),
          p("822729", "atletico_mineiro"),
          p("831778", "atletico_mineiro"),
        ],
      },
    ],
  },
  {
    id: "bahia",
    title: "Bahia",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Bahia no Brasileirão 2026.",
    accent: "#005ca9",
    groups: [
      {
        players: [
          p("874063", "bahia"),
          p("1008832", "bahia"),
        ],
      },
    ],
  },
  {
    id: "botafogo",
    title: "Botafogo",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Botafogo no Brasileirão 2026.",
    accent: "#1f1f1f",
    groups: [
      {
        players: [
          p("1650770", "botafogo"),
          p("221636", "botafogo"),
          p("1003010", "botafogo"),
        ],
      },
    ],
  },
  {
    id: "chapecoense",
    title: "Chapecoense",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Chapecoense no Brasileirão 2026.",
    accent: "#006633",
    groups: [
      {
        players: [
          p("975319", "chapecoense"),
          p("850475", "chapecoense"),
          p("1120738", "chapecoense"),
        ],
      },
    ],
  },
  {
    id: "corinthians",
    title: "Corinthians",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Corinthians no Brasileirão 2026.",
    accent: "#1a1a1a",
    groups: [
      {
        players: [
          p("994454", "corinthians"),
          p("1199261", "corinthians"),
          p("866392", "corinthians"),
        ],
      },
    ],
  },
  {
    id: "coritiba",
    title: "Coritiba",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Coritiba no Brasileirão 2026.",
    accent: "#006633",
    groups: [
      {
        players: [
          p("77726", "coritiba"),
          p("1111139", "coritiba"),
          p("925142", "coritiba"),
        ],
      },
    ],
  },
  {
    id: "cruzeiro",
    title: "Cruzeiro",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Cruzeiro no Brasileirão 2026.",
    accent: "#0033a0",
    groups: [
      {
        players: [
          p("912786", "cruzeiro"),
          p("611876", "cruzeiro"),
          p("377238", "cruzeiro"),
        ],
      },
    ],
  },
  {
    id: "flamengo",
    title: "Flamengo",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Flamengo no Brasileirão 2026.",
    accent: "#c8102e",
    groups: [
      {
        players: [
          p("1145106", "flamengo"),
          p("590392", "flamengo"),
          p("132874", "flamengo"),
        ],
      },
    ],
  },
  {
    id: "fluminense",
    title: "Fluminense",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Fluminense no Brasileirão 2026.",
    accent: "#7a263a",
    groups: [
      {
        players: [
          p("1104068", "fluminense"),
          p("548030", "fluminense"),
          p("1067671", "fluminense"),
        ],
      },
    ],
  },
  {
    id: "gremio",
    title: "Grêmio",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Grêmio no Brasileirão 2026.",
    accent: "#0099d8",
    groups: [
      {
        players: [
          p("1020375", "gremio"),
          p("989862", "gremio"),
          p("794927", "gremio"),
        ],
      },
    ],
  },
  {
    id: "internacional",
    title: "Internacional",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Internacional no Brasileirão 2026.",
    accent: "#c8102e",
    groups: [
      {
        players: [
          p("345113", "internacional"),
          p("879902", "internacional"),
          p("978563", "internacional"),
        ],
      },
    ],
  },
  {
    id: "mirassol",
    title: "Mirassol",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Mirassol no Brasileirão 2026.",
    accent: "#f4c430",
    groups: [
      {
        players: [
          p("988851", "mirassol"),
          p("874723", "mirassol"),
          p("1175760", "mirassol"),
        ],
      },
    ],
  },
  {
    id: "palmeiras",
    title: "Palmeiras",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Palmeiras no Brasileirão 2026.",
    accent: "#006437",
    groups: [
      {
        players: [
          p("285949", "palmeiras"),
          p("840202", "palmeiras"),
          p("331397", "palmeiras"),
        ],
      },
    ],
  },
  {
    id: "red_bull_bragantino",
    title: "Red Bull Bragantino",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Red Bull Bragantino no Brasileirão 2026.",
    accent: "#c8102e",
    groups: [
      {
        players: [
          p("1067641", "red_bull_bragantino"),
          p("242052", "red_bull_bragantino"),
          p("1463904", "red_bull_bragantino"),
        ],
      },
    ],
  },
  {
    id: "remo",
    title: "Remo",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Remo no Brasileirão 2026.",
    accent: "#0033a0",
    groups: [
      {
        players: [
          p("943044", "remo"),
          p("981350", "remo"),
          p("594428", "remo"),
        ],
      },
    ],
  },
  {
    id: "santos",
    title: "Santos",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Santos no Brasileirão 2026.",
    accent: "#1a1a1a",
    groups: [
      {
        players: [
          p("1656036", "santos"),
          p("922454", "santos"),
          p("242213", "santos"),
        ],
      },
    ],
  },
  {
    id: "sao_paulo",
    title: "São Paulo",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do São Paulo no Brasileirão 2026.",
    accent: "#c8102e",
    groups: [
      {
        players: [
          p("356514", "sao_paulo"),
          p("1015261", "sao_paulo"),
          p("905453", "sao_paulo"),
        ],
      },
    ],
  },
  {
    id: "vasco_da_gama",
    title: "Vasco da Gama",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Vasco da Gama no Brasileirão 2026.",
    accent: "#1a1a1a",
    groups: [
      {
        players: [
          p("1444694", "vasco_da_gama"),
          p("329303", "vasco_da_gama"),
          p("840398", "vasco_da_gama"),
        ],
      },
    ],
  },
  {
    id: "vitoria",
    title: "Vitória",
    subtitle: "Top 3 meio-campistas",
        description: "Os 3 meio-campistas com mais minutos do Vitória no Brasileirão 2026.",
    accent: "#c8102e",
    groups: [
      {
        players: [
          p("871032", "vitoria"),
          p("794312", "vitoria"),
          p("922575", "vitoria"),
        ],
      },
    ],
  },
];

export function allReportPlayerRefs(): ReportPlayerRef[] {
  const seen = new Set<string>();
  const out: ReportPlayerRef[] = [];
  for (const category of PLAYER_REPORT_CATEGORIES) {
    for (const group of category.groups) {
      for (const player of group.players) {
        if (seen.has(player.playerId)) continue;
        seen.add(player.playerId);
        out.push(player);
      }
    }
  }
  return out;
}

export function totalReportCount(): number {
  return allReportPlayerRefs().length;
}

export type EnrichedReportPlayer = ReportPlayerRef & {
  category: PlayerReportCategory;
  groupLabel?: string;
  categoryIndex: number;
};

export function enrichedReportPlayers(): EnrichedReportPlayer[] {
  const out: EnrichedReportPlayer[] = [];
  for (const category of PLAYER_REPORT_CATEGORIES) {
    let categoryIndex = 0;
    for (const group of category.groups) {
      for (const player of group.players) {
        categoryIndex += 1;
        out.push({
          ...player,
          category,
          groupLabel: group.label,
          categoryIndex,
        });
      }
    }
  }
  return out;
}

export function playerIdsForProfileGroup(groupId: string): Set<string> {
  if (groupId === PROFILE_ALL_GROUP.id) {
    return new Set(allReportPlayerRefs().map((p) => p.playerId));
  }
  const category = PLAYER_REPORT_CATEGORIES.find((cat) => cat.id === groupId);
  if (!category) return new Set();
  const ids = new Set<string>();
  for (const group of category.groups) {
    for (const player of group.players) {
      ids.add(player.playerId);
    }
  }
  return ids;
}

export function profileTeamCounts(
  players: { player_id?: string | number | null; team_key?: string | null }[],
): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const player of players) {
    const teamKey = String(player.team_key ?? "");
    if (!teamKey) continue;
    counts[teamKey] = (counts[teamKey] ?? 0) + 1;
  }
  return counts;
}

export function profileGroupCounts(
  players: { player_id?: string | number | null }[],
): Record<string, number> {
  const available = new Set(players.map((p) => String(p.player_id)));
  const counts: Record<string, number> = {
    [PROFILE_ALL_GROUP.id]: players.length,
  };
  for (const category of PLAYER_REPORT_CATEGORIES) {
    const ids = playerIdsForProfileGroup(category.id);
    counts[category.id] = [...ids].filter((id) => available.has(id)).length;
  }
  return counts;
}

export function teamKeyForPlayer(playerId: string): string | undefined {
  for (const category of PLAYER_REPORT_CATEGORIES) {
    const ids = playerIdsForProfileGroup(category.id);
    if (ids.has(playerId)) return category.id;
  }
  return undefined;
}
